sonar.projectKey=MariaLuizaMb_SpendSmart
sonar.organization=marialuizamb
sonar.host.url=https://sonarcloud.io

sonar.projectName=SpendSmart
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src,frontend/src,analytics/app
sonar.tests=backend/tests,frontend/tests,analytics/tests

sonar.exclusions=\
  backend/generated/**,\
  backend/prisma/migrations/**,\
  backend/src/scripts/**,\
  **/__pycache__/**,\
  **/*.pyc,\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**

sonar.coverage.exclusions=\
  backend/src/server.js,\
  frontend/src/main.jsx,\
  frontend/src/setupTests.js,\
  **/*.test.js,\
  **/*.test.jsx,\
  **/tests/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=analytics/coverage.xml


